{% set name = "nmslib" %}
{% set version = "2.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: baf1e1648ced605d4d67170776682431acfa9c1b9310650d7b58e573bfde5d5f

build:
  number: 0
  script: '{{ PYTHON }} -m pip install --no-deps --no-binary :all: .'

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - psutil
    - pip >=10
    - pybind11 >=2.2.3
    - numpy >=1.10.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pybind11 >=2.2.3

test:
  imports:
    - nmslib

about:
  home: https://github.com/searchivarius/nmslib
  summary: Non-Metric Space Library (NMSLIB)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jzthree
